### ISSUE TITLE
24h clock styling

### ISSUE THREAD

**Issue by PrtmPhlp** [reportaman/arttime#15]
I'm from Germany and here the time is 24h based. Would love a future Feature, where you can toggle between the 12 and 24 hour system. (Maybe directly in the _"set or reset timezone"_ menu)

**Comment by reportaman** [comment]
That would be a good feature to have, will definitely add that, perhaps coming week if I get time.

**Comment by reportaman** [comment]
@PrtmPhlp @cjk I have pushed the change in main branch. Pull and run install.sh again if you installed using method 2) or just copy paste and run the simple installer again (it automatically pulls main branch and merges) if you uses install method 1). https://github.com/reportaman/arttime#installation

There are 2 changes in UI:

1. A CLI new option --hours can be provided while invoking arttime with value 24 or 12 (default)*
2. A new keybinding ``f`` is added to toggle between 12 and 24 hour formats.

* I would recommend to alias ``alias arttime="arttime --hours 24 "`` for those who want 24 hours by default. In future arttime might parse user's locale to find whether they want 12 hour or 24 hour format if there is a compelling reason...

**Comment by PrtmPhlp** [comment]
Thank you so much. Works great.
