### ISSUE TITLE
Scrolling on FreeBSD 13.1-RELEASE-p2

### ISSUE THREAD

**Issue by grahamperrin** [reportaman/arttime#16]
Spun off from <https://old.reddit.com/r/freebsd/comments/xpyr0l/-/iq72rm0/?context=3>

```text
freebsd@freebsd:~/dev/arttime $ echo $TERM
xterm-256color
freebsd@freebsd:~/dev/arttime $ 
```

https://user-images.githubusercontent.com/192271/192857987-c29179b6-91d5-449d-9f37-fad9ee6253b5.mp4

**Comment by reportaman** [comment]
@grahamperrin Thanks! Can you please post the output of this command here: ``$ infocmp``?

**Comment by reportaman** [comment]
Update: I got my hands on FreeBSD 13.1, I'll do the rest...

**Comment by grahamperrin** [comment]
> … Please pull and give it a try, it should work well now …

Confirmed, working. Thanks!

**Comment by reportaman** [comment]
@grahamperrin Closing this as scrolling issue is fixed, let's carry forward the discussion about https://github.com/reportaman/arttime/issues/16#issuecomment-1263280574 in the other ticket you filed https://github.com/reportaman/arttime/issues/18. Its not an arttime bug, it might lead us to patching stale terminal databases being published... Though its very important path to pursue if we want users to not hit such issues, and developers to not bypass term databases and hack around them by embedding escape sequences (like vim, etc) in their applications going forward.
